"""
FastAPI backend (CDC continuation section 25/14).

Serves the DEMO_ONLY forecast dataset built by scripts/04 and (optionally)
05/06/07. Every forecast response carries data_source/forecast_status fields
so a client can never mistake demo output for validated real forecasts.

Run:
    uvicorn src.api.main:app --reload --port 8000
Docs:
    http://localhost:8000/docs (auto-generated by FastAPI)
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from src.aggregation.hierarchical import reconcile_all_levels, check_consistency
from src.ingestion.data_mode import get_data_mode
from src.monitoring.drift import weather_drift_report, production_drift_report, anomaly_flags
from src.forecasting.backtesting import evaluate

app = FastAPI(
    title="PESTGM 7.0 Track 1 - PV Forecast API (DEMO)",
    description="National PV forecasting platform for Tunisia. "
                 "DATA_MODE currently determines whether responses are demo-labelled.",
    version="0.2.0",
)

DATA_PATH = Path("data/processed/training_dataset_15min_sample.csv")
MODEL_VERSION = "demo-physics-lightgbm-0.2"

_CACHE: dict = {}


def _load() -> pd.DataFrame:
    if not DATA_PATH.exists():
        raise HTTPException(status_code=503, detail=f"{DATA_PATH} not built yet - run scripts/04.")
    if "df" not in _CACHE:
        _CACHE["df"] = pd.read_csv(DATA_PATH, parse_dates=["timestamp"])
    return _CACHE["df"]


class ForecastPoint(BaseModel):
    forecast_issue_time: str
    target_timestamp: str
    horizon: str
    spatial_level: str
    entity: str
    forecast_mw: float
    p10_mw: float | None = None
    p50_mw: float | None = None
    p90_mw: float | None = None
    model_version: str
    data_source: str
    forecast_status: str
    generation_time: str


class ForecastRequest(BaseModel):
    spatial_level: str  # district | governorate | national
    entity: str
    horizon: str = "intraday_15min"


def _data_source_label(df: pd.DataFrame) -> str:
    col = "pv_production_source"
    return df[col].iloc[0] if col in df.columns and len(df) else "UNKNOWN"


@app.get("/health")
def health():
    return {"status": "ok", "data_mode": get_data_mode().value, "time": datetime.now(timezone.utc).isoformat()}


@app.get("/districts")
def districts():
    df = _load()
    out = df.drop_duplicates("district_id")[["district_id", "district", "governorate", "latitude", "longitude"]]
    return out.to_dict(orient="records")


@app.get("/capacity")
def capacity(district_id: str | None = None):
    df = _load()
    if district_id:
        df = df[df["district_id"] == district_id]
        if df.empty:
            raise HTTPException(404, f"Unknown district_id {district_id}")
    latest = df.sort_values("timestamp").groupby("district_id").tail(1)
    return latest[["district_id", "district", "governorate", "timestamp", "capacity_mw", "capacity_source"]].to_dict(
        orient="records"
    )


def _points_from_series(sub: pd.DataFrame, level: str, entity: str, now: str) -> list[dict]:
    return [
        ForecastPoint(
            forecast_issue_time=now, target_timestamp=row["timestamp"].isoformat() if hasattr(row["timestamp"], "isoformat") else str(row["timestamp"]),
            horizon="intraday_15min", spatial_level=level, entity=entity,
            forecast_mw=float(row["pv_production_mw_proxy"]),
            model_version=MODEL_VERSION, data_source=_data_source_label(sub),
            forecast_status="DEMO_PROXY_PHYSICS_SIMULATION", generation_time=now,
        ).model_dump()
        for _, row in sub.iterrows()
    ]


@app.get("/forecast/district/{district_id}")
def forecast_district(district_id: str):
    df = _load()
    g = df[df["district_id"] == district_id]
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(g.sort_values("timestamp"), "district", district_id, now)


@app.get("/forecast/governorate/{governorate}")
def forecast_governorate(governorate: str):
    df = _load()
    g = df[df["governorate"] == governorate]
    if g.empty:
        raise HTTPException(404, f"Unknown governorate {governorate}")
    levels = reconcile_all_levels(g, "pv_production_mw_proxy")
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(levels["governorate"], "governorate", governorate, now)


@app.get("/forecast/national")
def forecast_national():
    df = _load()
    levels = reconcile_all_levels(df, "pv_production_mw_proxy")
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(levels["national"], "national", "TUNISIA", now)


@app.post("/forecast")
def post_forecast(req: ForecastRequest):
    """Generic forecast endpoint: dispatches to the district/governorate/national
    getters above based on the request body (CDC-required POST /forecast)."""
    if req.spatial_level == "district":
        return forecast_district(req.entity)
    if req.spatial_level == "governorate":
        return forecast_governorate(req.entity)
    if req.spatial_level == "national":
        return forecast_national()
    raise HTTPException(400, "spatial_level must be one of district|governorate|national")


@app.get("/uncertainty")
def uncertainty(district_id: str):
    """DEMO_ONLY placeholder: point forecast +/- a fixed illustrative band
    derived from the target's own short-term volatility (not a fitted
    quantile model at API-serve time, to keep the endpoint fast; the fitted
    quantile-model results live in reports/MODEL_VALIDATION_REPORT.md and
    reports/MULTI_HORIZON_REPORT.md)."""
    df = _load()
    g = df[df["district_id"] == district_id].sort_values("timestamp")
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
    std = g["pv_production_mw_proxy"].rolling(8, min_periods=1).std().fillna(0)
    out = g[["timestamp", "pv_production_mw_proxy"]].copy()
    out["p10_mw"] = (g["pv_production_mw_proxy"] - 1.2816 * std).clip(lower=0)
    out["p90_mw"] = (g["pv_production_mw_proxy"] + 1.2816 * std).clip(upper=g["capacity_mw"])
    out["note"] = "illustrative band from rolling std, NOT the fitted conformal quantile model"
    return out.to_dict(orient="records")


@app.get("/errors")
def errors(district_id: str):
    """Forecast-vs-actual error using persistence as the stand-in 'forecast'
    (DEMO_ONLY - a genuine ML-forecast-vs-actual log requires the scripts/05-07
    pipeline artifacts; this endpoint demonstrates the schema and computation)."""
    df = _load()
    g = df[df["district_id"] == district_id].sort_values("timestamp").copy()
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
    g["persistence_forecast_mw"] = g["pv_production_mw_proxy"].shift(1)
    g = g.dropna(subset=["persistence_forecast_mw"])
    m = evaluate(g["pv_production_mw_proxy"], g["persistence_forecast_mw"], g["capacity_mw"])
    return {"district_id": district_id, "baseline": "persistence", "metrics": m}


@app.get("/anomalies")
def anomalies(district_id: str | None = None):
    df = _load()
    if district_id:
        df = df[df["district_id"] == district_id]
        if df.empty:
            raise HTTPException(404, f"Unknown district_id {district_id}")
    flags = anomaly_flags(df, production_col="pv_production_mw_proxy")
    flagged = flags[flags["physical_anomaly_flag"]]
    return {
        "n_checked": len(flags),
        "n_flagged": len(flagged),
        "pct_flagged": round(100 * len(flagged) / max(len(flags), 1), 3),
        "sample_flagged_rows": flagged.head(20).to_dict(orient="records"),
    }


@app.get("/drift/weather")
def drift_weather():
    df = _load()
    ref_end = df["timestamp"].quantile(0.5)
    report = weather_drift_report(df, ref_end)
    return report.to_dict(orient="records")


@app.get("/drift/production")
def drift_production():
    df = _load()
    ref_end = df["timestamp"].quantile(0.5)
    return production_drift_report(df, "pv_production_mw_proxy", ref_end)


@app.get("/export")
def export(spatial_level: str = Query("national"), entity: str = Query("TUNISIA"), fmt: str = Query("json")):
    """Grid/load-forecasting integration export (CDC Phase 15). fmt=json|csv."""
    if spatial_level == "district":
        data = forecast_district(entity)
    elif spatial_level == "governorate":
        data = forecast_governorate(entity)
    else:
        data = forecast_national()
    if fmt == "csv":
        buf = io.StringIO()
        pd.DataFrame(data).to_csv(buf, index=False)
        buf.seek(0)
        return StreamingResponse(buf, media_type="text/csv",
                                  headers={"Content-Disposition": f"attachment; filename={spatial_level}_{entity}.csv"})
    return data


@app.get("/model/status")
def model_status():
    return {
        "model_version": MODEL_VERSION,
        "data_mode": get_data_mode().value,
        "trained_on": "DEMO_PROXY_PHYSICS_SIMULATION (see docs/DATA_READINESS_REPORT.md)",
        "note": "Not validated against real STEG production - see docs/REAL_PRODUCTION_DATA_SOURCES.md",
    }
